
-- medium henge

-- structure setup
local i = {name="ignore"}
local a = {name="air"}

local j = {name="default:dirt_with_grass"}
local k = {name="default:cobble"}
local l = {name="default:stone"}
local m = {name="stairs:slab_stone"}

local avoid_short_nodes = {
	core.get_content_id("default:tree"),
	core.get_content_id("default:jungletree"),
	core.get_content_id("default:pine_tree"),
	core.get_content_id("default:water_source"),
	core.get_content_id("default:water_flowing"),
	core.get_content_id("default:river_water_source"),
	core.get_content_id("default:river_water_flowing")
}
if core.get_modpath("valleys_c") then
	avoid_short_nodes[#avoid_short_nodes+1] = core.get_content_id("valleys_c:birch_tree")
	avoid_short_nodes[#avoid_short_nodes+1] = core.get_content_id("valleys_c:fir_tree")
	avoid_short_nodes[#avoid_short_nodes+1] = core.get_content_id("valleys_c:banana_tree")
	avoid_short_nodes[#avoid_short_nodes+1] = core.get_content_id("valleys_c:cherry_blossom_tree")
	avoid_short_nodes[#avoid_short_nodes+1] = core.get_content_id("valleys_c:fern_trunk_big")
	avoid_short_nodes[#avoid_short_nodes+1] = core.get_content_id("valleys_c:water_source")
	avoid_short_nodes[#avoid_short_nodes+1] = core.get_content_id("valleys_c:water_flowing")
	avoid_short_nodes[#avoid_short_nodes+1] = core.get_content_id("valleys_c:river_water_source")
	avoid_short_nodes[#avoid_short_nodes+1] = core.get_content_id("valleys_c:river_water_flowing")
end

local avoid_long_nodes = {
	core.get_content_id("default:cobble")
}

local chest_items = {
	{name="default:apple", max = 3},
	{name="farming:bread", max = 3},
	{name="default:steel_ingot", max = 2},
	{name="default:gold_ingot", max = 2},
	{name="default:diamond", max = 1},
	{name="default:pick_steel", max = 1}
}

-- structure definition
structures:add_structure("md_henge", {
	where_in = core.get_content_id("default:dirt_with_grass"),
	avoid_short = {
		distance = 5,
		nodes = avoid_short_nodes
	},
	avoid_long = avoid_long_nodes,
	offset = {x=0, y=0, z=0},
	schematic = {
		size = {x=31, y=11, z=31},
		data = {
			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			
			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			
			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			
			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,
			i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,
			i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,a,a,a,a,a,a,l,a,l,a,a,a,a,a,a,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,a,a,a,a,a,a,l,a,l,a,a,a,a,a,a,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,a,a,a,a,a,a,l,a,l,a,a,a,a,a,a,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,a,a,a,a,a,a,l,l,l,a,a,a,a,a,a,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,
			i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,
			i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,a,a,a,a,m,a,a,a,a,a,a,a,m,a,a,a,a,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,
			i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,
			i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,k,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,l,a,a,a,a,a,a,a,a,a,a,a,l,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,l,a,a,a,a,a,a,a,a,a,a,a,l,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,l,a,a,a,a,a,a,a,a,a,a,a,l,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,k,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,k,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,
			i,i,i,i,i,a,a,m,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,m,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,j,j,j,j,j,j,j,j,j,j,k,k,k,j,j,j,j,j,j,j,j,j,j,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,j,j,j,j,j,j,j,j,j,k,k,k,k,k,j,j,j,j,j,j,j,j,j,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,m,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,j,j,j,j,j,j,j,j,k,k,k,k,k,k,k,j,j,j,j,j,j,j,j,i,i,i,i,
			i,i,i,i,a,a,l,a,a,a,a,a,a,a,l,l,l,a,a,a,a,a,a,a,l,a,a,i,i,i,i,
			i,i,i,i,a,a,l,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,l,a,a,i,i,i,i,
			i,i,i,i,a,a,l,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,l,a,a,i,i,i,i,
			i,i,i,i,a,a,l,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,l,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,j,j,j,j,j,k,k,k,k,k,k,k,k,k,k,k,k,k,j,j,j,j,j,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,m,l,l,l,m,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,l,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,l,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,j,j,j,j,j,j,j,j,k,k,k,k,k,k,k,j,j,j,j,j,j,j,j,i,i,i,i,
			i,i,i,i,a,a,l,a,a,a,a,a,a,a,l,l,l,a,a,a,a,a,a,a,l,a,a,i,i,i,i,
			i,i,i,i,a,a,l,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,l,a,a,i,i,i,i,
			i,i,i,i,a,a,l,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,l,a,a,i,i,i,i,
			i,i,i,i,a,a,l,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,l,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,j,j,j,j,j,j,j,j,j,k,k,k,k,k,j,j,j,j,j,j,j,j,j,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,m,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,j,j,j,j,j,j,j,j,j,j,k,k,k,j,j,j,j,j,j,j,j,j,j,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,
			i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,k,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,
			i,i,i,i,i,a,a,m,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,m,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,k,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,
			i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,
			i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,k,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,l,a,a,a,a,a,a,a,a,a,a,a,l,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,l,a,a,a,a,a,a,a,a,a,a,a,l,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,l,a,a,a,a,a,a,a,a,a,a,a,l,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,
			i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,
			i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,
			i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,
			i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,a,a,a,a,m,a,a,a,a,a,a,a,m,a,a,a,a,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,
			i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,a,a,a,a,a,a,l,a,l,a,a,a,a,a,a,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,a,a,a,a,a,a,l,a,l,a,a,a,a,a,a,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,a,a,a,a,a,a,l,a,l,a,a,a,a,a,a,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,a,a,a,a,a,a,l,l,l,a,a,a,a,a,a,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,
			i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,
			i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,

			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,a,a,a,a,a,a,a,i,i,i,i,i,i,i,i,i,i,i,i,
			
			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,
			i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			
			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			
			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,i,i,i,i,i,i,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			
			j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
			i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,i,
		}
	}
})